### ISSUE TITLE
Language change for ZUTBeamer?

### ISSUE THREAD

**Issue by Ceebs93** [karlosos/ZUTBeamer#5]
Hi,

Sorry to bother you with something so small but I can't seem to find a way to change the language used by ZUTBeamer to english, so that \supervisor would output supervisor and not promoter etc. I tried the most obvious thing first, removing the line " \usepackage[main=polish]{babel}" Which worked for basic commands such as \date but not for others such as \supervisor. Is the language built into these commands (which I assume you defined as part of the template?), I can't see anything that seems relevant to it in beamerthemezut.sty.

Kind regards,
Ciara

**Comment by karlosos** [comment]
Thanks for finding this! You are correct. Currently, those texts are hardcoded into the template. As a quick fix, you can change `\supervisor` prefix from "Promotor" to your language in file [zutbeamer/beamerinnerthemezutbeamer.sty](https://github.com/karlosos/ZUTBeamer/blob/main/zutbeamer/beamerinnerthemezutbeamer.sty#L51). The same goes for changing `\goal` prefix. 

In the same [file](https://github.com/karlosos/ZUTBeamer/blob/main/zutbeamer/beamerinnerthemezutbeamer.sty#L10), you can change paths to logos used in the sidebar.

**Comment by Ceebs93** [comment]
Ah thank-you! I really appreciate you getting back to me so quickly!
